In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
engine = create_engine("sqlite:///../superstore.db")

In [9]:
df = pd.read_sql("SELECT * FROM superstore", engine)

In [10]:
print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [11]:
print(df.shape)

(9994, 21)

In [12]:
query = """
SELECT "Product Name",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

top_products = pd.read_sql(query, engine)
top_products

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [13]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category;
"""

category_sales = pd.read_sql(query, engine)
category_sales

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [14]:
query = """
SELECT "Customer Name",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

top_customers = pd.read_sql(query, engine)
top_customers

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

In [15]:
query = """
SELECT Region,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Region;
"""

region_profit = pd.read_sql(query, engine)
region_profit

    Region  Total_Profit
0  Central    39706.3625
1     East    91522.7800
2    South    46749.4303
3     West   108418.4489

In [16]:
query = """
SELECT "Order Date", Sales
FROM superstore;
"""

monthly_sales = pd.read_sql(query, engine)
monthly_sales.head()

   Order Date     Sales
0  2016-11-08  261.9600
1  2016-11-08  731.9400
2  2016-06-12   14.6200
3  2015-10-11  957.5775
4  2015-10-11   22.3680